#!/usr/bin/env bash
# install-packages.sh — Tracked, durable entry point for Pi package management.
#
# This script is the single durable mechanism for installing Pi packages
# and applying committed patches. It must be used instead of bare `pi install`
# or bare `npm install` to ensure:
#   - Project-local package installation under .pi/npm/
#   - Project-agent override support (patched pi-subagents)
#   - Legacy .agents/ exclusion from agent discovery (patched pi-subagents)
#
# Usage:
#   bash .pi/install-packages.sh          # full install + patch
#   bash .pi/install-packages.sh --patch  # re-apply patches only (no install)
#
# Durability:
#   - This script is tracked in git.
#   - .pi/patches/ directory is tracked in git.
#   - .pi/npm/ is gitignored and regenerated by this script.
#   - After clean clone, running this script gives a fully patched environment.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NPM_DIR="$PROJECT_ROOT/.pi/npm"
PATCHES_DIR="$PROJECT_ROOT/.pi/patches"
SETTINGS_FILE="$PROJECT_ROOT/.pi/settings.json"

action="${1:-install}"

if [ "$action" = "--patch" ]; then
  echo "install-packages: Re-applying patches only..."
else
  echo "install-packages: Setting up project-local package installation..."

  # Ensure .pi/npm/ directory exists with gitignore
  mkdir -p "$NPM_DIR"
  if [ ! -f "$NPM_DIR/.gitignore" ]; then
    cat > "$NPM_DIR/.gitignore" << 'GITIGNORE'
*
!.gitignore
GITIGNORE
  fi

  # Create/update .pi/npm/package.json from project settings.
  # The postinstall hook ensures patches are applied after any npm operation.
  python3 -c "
import json, re, sys

settings_path = '$SETTINGS_FILE'.replace('\$', '\\\\$')
npm_dir = '$NPM_DIR'.replace('\$', '\\\\$')

# Read project settings to get package list
with open(settings_path) as f:
    settings = json.load(f)

packages = settings.get('packages', [])
deps = {}
for pkg in packages:
    if pkg.startswith('npm:'):
        spec = pkg[4:]  # remove 'npm:' prefix
        # Split name@version. Preserve exact pins from .pi/settings.json;
        # package restores must not float to a newer compatible version.
        if '@' in spec:
            name, version = spec.rsplit('@', 1)
            if not re.match(r'^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$', version):
                raise SystemExit(f'install-packages: ERROR: npm package {pkg!r} must use an exact semver pin')
            deps[name] = version
        else:
            raise SystemExit(f'install-packages: ERROR: npm package {pkg!r} must include an exact version pin')

# Create package.json with postinstall hook
pkg_json = {
    'name': 'pi-extensions',
    'private': True,
    'dependencies': deps,
    'scripts': {
        'postinstall': 'bash ../patches/apply-patches.sh'
    }
}

import os
pkg_path = os.path.join(npm_dir, 'package.json')
with open(pkg_path, 'w') as f:
    json.dump(pkg_json, f, indent=2)
    f.write('\n')

print(f'install-packages: Created {pkg_path} with deps: {list(deps.keys())}')
"

  echo "install-packages: Running npm install in .pi/npm/..."
  npm install --prefix "$NPM_DIR" --no-fund --no-audit 2>&1

  installed_version="$(node -p "require('$NPM_DIR/node_modules/pi-subagents/package.json').version" 2>/dev/null || true)"
  if [ "$installed_version" != "0.24.2" ]; then
    echo "install-packages: ERROR: expected pi-subagents@0.24.2, installed '${installed_version:-missing}'" >&2
    exit 1
  fi
  echo "install-packages: Verified pi-subagents@${installed_version}"
fi

# Apply committed patches (also injects postinstall hook if needed)
echo "install-packages: Applying committed patches..."
if [ -f "$PATCHES_DIR/apply-patches.sh" ]; then
  bash "$PATCHES_DIR/apply-patches.sh"
else
  echo "install-packages: ERROR: No apply-patches.sh found at $PATCHES_DIR" >&2
  exit 1
fi

echo "install-packages: Done. Verify with: PI_TELEMETRY=0 pi list"
